name: auto-semver-actions
on: [push]
env:
  GITHUB_URL: 'git@github.com:RightBrain-Networks/auto-semver.git'
  GITHUB_KEY: 'rbn-ops github'

  SERVICE: 'auto-semver'
  SELF_SEMVER_TAG: "master"
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Run Auto-Semver
        id: semver
        uses: RightBrain-Networks/semver-action@1.0.0
        with:
          mode: set
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: build
        run: |
          python setup.py sdist
      #- name: test
       # run: |
        #  python tests.py
        #working-directory: semver
    CheckVersion:
      runs-on: ubuntu-latest
      needs: build
      steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Auto-Semver          
        id: semver
        uses: RightBrain-Networks/semver-action@1.0.0
        with:
          mode: set
      - name: Create Release
        uses: actions/create-release@v2
        if: steps['semver']['outputs']['RETURN_STATUS'] == '0'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.semver.outputs.SEMVER_NEW_VERSION }}
          release_name: ${{ steps.semver.outputs.SEMVER_NEW_VERSION }}
          body: Version ${{ steps.semver.outputs.SEMVER_NEW_VERSION }} released automatically by [RightBrain-Networks/auto-semver](https://github.com/RightBrain-Networks/auto-semver)
          draft: false
          prerelease: false